### PR TITLE
Switch over to GitHub Actions and fix various issues with the test suite

### PR DESCRIPTION
**Pull request by judofyr**
This is in order to prepare a new release.

@ntkme: Could you have a look at this and see if it makes sense?

Pending work to make all tests work:

- [x] Workaround this JRuby bug: https://github.com/jruby/jruby/issues/7272
- [x] Figure out why RDiscount doesn't support smart settings in the CI: https://github.com/rtomayko/tilt/runs/7396767676?check_suite_focus=true. This passes locally on my Mac.

### CODE REVIEW

**Review by ntkme — COMMENTED** [review]
LGTM except the two issues you already found. I will do some test for RDiscount in my environment and see if I can reproduce it.

**Comment by ntkme** [comment]
The issue is that both bluecloth and rdiscount are bundling a native extension for discount. bluecloth bundles 2.0.6 but rdiscount bundles 2.2.0. I think the best way to deal with it is to isolate the two from being tested together.

**Comment by judofyr** [comment]
Alrighty, @ntkme, I think I've fixed all the problems now! Looks good?

**Review by ntkme — APPROVED** [review]
LGTM!

**Pull request merged**
