### PR TITLE
Add Mapping#unregister(*extensions)

### LINKED ISSUE #330: How to remove mapping
Hi, I'm using tilt within [middleman](https://github.com/middleman/middleman).

In my situation, I don't want '.rst' files in my source to path renderer, and want to remove 'rst' from mappings.

I found the good tips [here](https://github.com/middleman/middleman/issues/822) like...

```
Tilt.mappings.delete('rst')
```

But this couldn't work, maybe because it's for the older version of tilt.
I'm using tilt v2.0.8.

I looked into source code, but couldn't find the way to remove the specific mapping from outside.
Any idea?

Thank you.

### PR DESCRIPTION
**Pull request by jeremyevans**
This makes it simpler to remove already registered extensions.

Fixes #330

### CODE REVIEW

**Review by judofyr — APPROVED** [review]
LGTM!

Should we also provide `Tilt.unregister`? 🤔 I'm not sure if we want to rather promote the use of `Tilt.default_mapping` or introduce more `Tilt`-level methods?

**Comment by judofyr** [comment]
(Note: This now has a conflict with `master`)

**Comment by jeremyevans** [comment]
> Should we also provide `Tilt.unregister`? 🤔 I'm not sure if we want to rather promote the use of `Tilt.default_mapping` or introduce more `Tilt`-level methods?

I doubt this method will be used much, so I don't think it is necessary.  However, I don't have objections to adding it.

I rebased this so I can be merged.

**Comment by judofyr** [comment]
Aaand I merged the minitest/spec so now this out of date again 🙃

**Comment by jeremyevans** [comment]
No problem, I'll rebase later today.

**Comment by jeremyevans** [comment]
OK, this has been rebased.

**Pull request merged**
