### PR TITLE
Add CommonMarker to README.md

### PR DESCRIPTION
**Pull request by raphink**

### CODE REVIEW

**Comment by judofyr** [comment]
The CommonMarker isn't actually registered with any extensions though: https://github.com/rtomayko/tilt/blob/02382457bbfdc4768968ca68ea50710eb7e5fd7e/lib/tilt.rb#L121

**Comment by raphink** [comment]
Oh right, I missed that, I'll add it.

**Comment by raphink** [comment]
There you go!

**Comment by judofyr** [comment]
Thanks for the patch!

**Pull request merged**
