### PR TITLE
Use Haml 5's new API to avoid using deprecated private method.

### PR DESCRIPTION
**Pull request by k0kubun**
Fixes https://github.com/rtomayko/tilt/issues/311

In https://github.com/haml/haml/pull/896, I've already implemented API exactly for this issue. After this change is released by tilt, I'll change Haml to depend on tilt after that version. Hopefully it'll be Haml 5.0.0.

### CODE REVIEW

**Comment by muellerj** [comment]
Hi @rtomayko, 

any chance of merging this? I'm having the same depreciation warning as described in #311 and would like to get the test output readable again :smiley:

**Comment by muellerj** [comment]
Awesome, thank you. Could you ping this thread once you release the next version?

**Comment by baelter** [comment]
Still getting this using tilt 2.0.8 with haml 4.0.7

**Comment by k0kubun** [comment]
Haml 4 in in maintenance mode and it can't have the same API used to resolve this issue. Why don't you use Haml 5?

**Pull request merged**
