### PR TITLE
Work with ruby 2.3's --enable-frozen-string-literal

### PR DESCRIPTION
**Pull request by jeremyevans**
These changes are the minimal ones necessary to allow Roda's specs
to pass.  There may well be other changes that are required.

### CODE REVIEW

**Comment by judofyr** [comment]
Is it possible to enable it by an environment variable? RUBYOPTS? That would make it possible to add it to the Travis build. Although it might be a bad idea because many of the other template engines might fail.

**Comment by judofyr** [comment]
I guess a custom entry with:

* Ruby 2.3
* RUBYOPTS=...
* Without both primary and secondary. That would only test the libraries that are shipped with Ruby.

**Comment by judofyr** [comment]
(And yes, JRuby errors are expected at the moment, so don't worry about those)

**Comment by jeremyevans** [comment]
You could enable testing on Travis, but in general it's going to be a very slow way to debug things if you want to be sure it works with any non-stdlib dependencies.  The only sane way to debug these issues in my opinion is to checkout all the dependencies locally, set `RUBYLIB` to contain the path to all of the dependency's `lib` directories, then run the specs with `--enable-frozen-string-literal --debug=frozen-string-literal`.  That shows the locations of all of the frozen strings that should probably be made unfrozen (or otherwise handled).  Then you have to deal with libraries that swallow exceptions (setting `$DEBUG = true` helps for those).

**Comment by judofyr** [comment]
If it's not in the test suite I'm not going to actively make it work (because I won't know when it breaks). If that's fine by you, I'll happily merge this (and any other similar pull request).

**Comment by jeremyevans** [comment]
That is fine by me.  I don't think it should be added to the test suite until someone has done the initial work of making sure all of the tilt specs pass with`--enable-frozen-string-literal`, which first requires that all dependencies have been fixed.

**Comment by judofyr** [comment]
Okay. Just keeping opening issues and/or pull request if you need something more.

**Pull request merged**
