### PR TITLE
Add Prawn PDF support

### PR DESCRIPTION
**Pull request by kematzy**
Hi, 

I took some time to add [Prawn PDF](http://prawnpdf.org/) support for Tilt so that it's built-in.

Hopefully, this PR can be accepted and incorporated.

Regards,

Kematzy

### CODE REVIEW

**Comment by kematzy** [comment]
Hallo, 

Any chance of some feedback, please?

**Comment by judofyr** [comment]
Looks good! Merged!

**Comment by judofyr** [comment]
Note: It's been merged (but rebased, that's why Github Issues doens't mark this as merged).

**Comment by kematzy** [comment]
Thanks! Much appreciated.

**Pull request closed without merging**
