### PR TITLE
Coverable templates

### PR DESCRIPTION
**Pull request by jeremyevans**
Ruby's coverage library does not support code loaded eval (and
similar methods like {class,module,instance}_{eval,exec}).  However,
it would be nice to be able to get code coverage for your web
application views.  One simple way to do this is to write a file
with the compiled template code, and then require it.  This is
an example of what that could look like.

I want to see if having coverable templates would be considered a
desirable feature in tilt. If it is a desirable feature, I can
work on an acceptable implementation.

### CODE REVIEW

**Comment by judofyr** [comment]
Wow, very interesting concept! I'm definitely open to adding support for this in 2.1.0.

My main concern is adding it in an opt-in way. It's a bit tricky now since `Template`-instances are very standalone and we don't have a generic "context" that we can configure.

One idea:
* We could have an `attr_accessor :compiled_path` on `Template`. When this is set, this is the file which we will write to to evaluate it.
* `Tilt::Mapping` could have an `attr_accessor :compile_directory`. When this is set, `Mapping#new` will automatically set `:compiled_path` based on this.

This means that by default there's no coverage support. You can do `Tilt.default_mapping.compile_directory = …` to enable it globally for anything which using the global `Tilt`-instance (as long as they use `Tilt.new`). And you can also set it directly on a single `Tilt::Mapping`.

**Comment by jeremyevans** [comment]
That approach sounds good.  I'll work on an implementation and tests next week.

**Comment by jeremyevans** [comment]
OK, I have an implementation ready for review.  I've tested it with one of my small apps (~5 views), with some updates to Roda and Erubi, and it helped find an uncovered branch in one view.  So it's already adding value.

I only added `Template#compiled_path` accessor.  I don't think `Tilt::Mapping#compile_directory` makes sense, as there is no linking of Template to the mapping the template came from, and the same template class can be in multiple mappings.  There could potentially be a global `Tilt.compile_directory` if you want.  Should be simple to add later if you want it.

Note that `compile_path` operates as a prefix and not a full path.  The same template can be rendered with multiple scope class/local variable combinations, each of which need their own files.

**Comment by jeremyevans** [comment]
@judofyr Have you had a chance to review this?  I'm not sure about including the scope class and local keys in the file name.  Almost all templates would just compile a single file, and for multiple compiled files, we could use an incrementing integer as the extension to differentiate them.  There's not a reason the file name must reflect the content, though maybe it makes things easier in certain cases.

Also, not sure if you are looking for a co-maintainer, but if you are, I can offer my services.  I could review pull requests, triage and fix the existing issues, cleanup code, get to 100% line/branch coverage, etc..

**Comment by judofyr** [comment]
> Have you had a chance to review this?

I've been a bit busy so I haven't been able to test out the code locally yet. Hoping to do it some time this week.

> I'm not sure about including the scope class and local keys in the file name. Almost all templates would just compile a single file, and for multiple compiled files, we could use an incrementing integer as the extension to differentiate them. There's not a reason the file name must reflect the content, though maybe it makes things easier in certain cases.

Is it possible to append to the same file and load it multiple times? How does the coverage tooling handle that? Does it "magically" merge them together? If so, that might be more user friendly instead of having a bunch of different files. (We'd have to figure out some smart way so that after `load`-ing it the second time it doesn't re-define the method.)

> Also, not sure if you are looking for a co-maintainer, but if you are, I can offer my services. I could review pull requests, triage and fix the existing issues, cleanup code, get to 100% line/branch coverage, etc..

Definitely looking for a co-maintainer. I have way too many other hobbies and this project definitely doesn't get the attention it deserves. I think it would help Tilt a lot if you had commit- and release-access.

**Comment by jeremyevans** [comment]
> > Have you had a chance to review this?
> 
> I've been a bit busy so I haven't been able to test out the code locally yet. Hoping to do it some time this week.

Sounds good.

> > I'm not sure about including the scope class and local keys in the file name. Almost all templates would just compile a single file, and for multiple compiled files, we could use an incrementing integer as the extension to differentiate them. There's not a reason the file name must reflect the content, though maybe it makes things easier in certain cases.
> 
> Is it possible to append to the same file and load it multiple times? How does the coverage tooling handle that? Does it "magically" merge them together? If so, that might be more user friendly instead of having a bunch of different files. (We'd have to figure out some smart way so that after `load`-ing it the second time it doesn't re-define the method.)

Unfortunately, this is not possible without additional changes.  The method name used is `"__tilt_#{Thread.current.object_id.abs}"`, which is the same for all methods tilt compiles in the current thread.  Tilt uses `eval` (or optionally `load` with this pull request) for the code that defines the method, then immediately gets the UnboundMethod for the method, then removes the method. So you cannot have multiple methods in the same file with the current design.

At this point, I would rather not change the internals too much just for the coverage feature.  So writing separate files per compiled method and loading them seems a better approach to me.  I do think the incrementing integer is a better approach then trying to include scope_class name and locals, so I'll push a commit to switch to that.

> > Also, not sure if you are looking for a co-maintainer, but if you are, I can offer my services. I could review pull requests, triage and fix the existing issues, cleanup code, get to 100% line/branch coverage, etc..
> 
> Definitely looking for a co-maintainer. I have way too many other hobbies and this project definitely doesn't get the attention it deserves. I think it would help Tilt a lot if you had commit- and release-access.

That sounds great.  I'll start work on pull request review and issue triaging.

**Comment by judofyr** [comment]
> That sounds great. I'll start work on pull request review and issue triaging.

Great work so far! Unfortunately I don't have admin access here to the GitHub repo so I can't add you as a contributor. I think @rtomayko can only do that.

However, it's been a lot easier to close/merge issues/PRs when you've already done the review. I also gave some feedback on some of the other functionality that you've provided.

Do you hang out in IRC-like place somewhere? Maybe we could sync up some time and talk more about how to proceed development here.

**Comment by jeremyevans** [comment]
I'm on the Bundler slack (among other things, that is where rack development is coordinated).  I think I can send you an invite to that if you are interested.

Looks like I need to update this PR to fix the conflicts, that should be simple.

**Comment by jeremyevans** [comment]
This has also been rebased after the switch to minitest/spec.

**Pull request merged**
